### ISSUE TITLE
Rotated electrodes in ds003645

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#201] opened 2024-03-18 21:35 UTC
I have checked that the import is OK 

https://github.com/sccn/eeglab/issues/747

Maybe run the export script again @dungscout96

**Comment by dungscout96** [comment] 2024-04-16 21:37
In the original version of the export script, there's seem to be a line to change the nose direction
`EEG = pop_chanedit(EEG,'nosedir','+Y');`
I re-exported the data and re-ran the pipeline. Looking at the processed data, it seems that the command didn't change the nose direction. 

I tested with two different set files, one from a different dataset. The field `nosedir: '+X'` in `EEG.chaninfo` doesn't change after running the command, with a message `Note for expert users: Nose direction is now set from '+Y' to default +X in EEG.chanlocs`. Is this the expected behavior?

**Comment by dungscout96** [comment] 2024-04-17 18:53
After discussing with Arnaud this behavior is ok and the nose direction has actually been correct. The issue might lie somewhere else in the export script or BIDS tool

**Comment by dungscout96** [comment] 2024-04-18 17:33
The issue can be fixed by #208

**Comment by dungscout96** [comment] 2024-05-07 17:39
Duplicate of https://github.com/sccn/NEMAR-pipeline/issues/72

**Closed by dungscout96** 2024-05-07 17:39 UTC
