### ISSUE TITLE
Cedric issue with special characters in groups

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#66] opened 2021-03-16 23:19 UTC
Probably need to force nonunicode characters. @amisepa could you upload small study for testing and describe how to reproduce the problem?

**Comment by amisepa** [comment] 2021-03-16 23:58
1) In EEGLAB GUI: 
Bids_tools > Import BIDS folder to STUDY > don't check any box and remove 'derivatives' at end of the path > Ok
2) STUDY > Edit study info
--> group info is not recognized:
![image](https://user-images.githubusercontent.com/58382227/111394767-97729b00-8678-11eb-9275-5e41f9ba5ec2.png)

--> but recognized in design variables fro .tsv file

BIDS folder was made using the bids_export function
Group was defined in both the data structure (numeric) and pInfo (character)

Cedric

**Comment by arnodelorme** [comment] 2021-03-22 23:54
@cll008 would you mind having a look?

**Comment by arnodelorme** [comment] 2021-04-01 00:52
@amisepa would you mind sharing the data again here? The data you share with me yesterday is also corrupted.

**Comment by amisepa** [comment] 2021-04-01 19:24
I redid it. This one works for me with latest pull: https://drive.google.com/file/d/1LkF5z9LWKUP-tNEIv3Mjlk72vhynY3d2/view?usp=sharing
with 
`[STUDY, ALLEEG] = pop_importbids('path\bids_test_group', 'eventtype','value','bidsevent','off','bidschanloc','off','outputdir','path\\bids_test_group\\');`
Note that it does not work if you have events ON as I don't use that option. Maybe that's why it didn't work before.

**Comment by cll008** [comment] 2021-04-05 21:14
Thanks @amisepa - I can load the latest data. You mentioned using `numeric` and `character` for defining group - is the issue title inaccurate? This isn't a special character usage issue is it?

@arnodelorme @dungscout96 It looks like neither bids export nor import explicitly refers to EEG.group. I think we should rely on pInfo and not EEG.group when exporting. However, on import we could strcmpi() pInfo for a `group` column and fill EEG.group. Don't think that would lead to any conflicts.

**Comment by arnodelorme** [comment] 2021-04-05 23:13
@amisepa. Link still does not work for me. Tried on WIndows and Mac. You are using a special compression program. Don't. Clement was able to uncompress and reshared with me.

**Comment by arnodelorme** [comment] 2021-04-06 00:31
The issue with data epochs was fixed. Please try and check that it works now.

**Comment by amisepa** [comment] 2021-04-06 16:23
I redid it. This one works for me with latest pull: https://drive.google.com/file/d/1LkF5z9LWKUP-tNEIv3Mjlk72vhynY3d2/view?usp=sharing
with 
`[STUDY, ALLEEG] = pop_importbids('path\bids_test_group', 'eventtype','value','bidsevent','off','bidschanloc','off','outputdir','path\\bids_test_group\\');`
Note that it does not work if you have events ON as I don't use that option. Maybe that's why it didn't work before.

**Comment by amisepa** [comment] 2021-04-06 16:58
Sorry I didn't mean to close the issue. 

@arnodelorme Data epochs? This is for something else I'm guessing. 
Here is a new link: 
I haven't compressed it this time so that should avoid the problem. I need to look into my compression settings.

@cll008 No special character no I only used either character '1' or numeric 1 for group variable in the script for bids_export. I referred to the little cube symbol in STUDY>info (see my screenshot above). Sorry if it was confusing.  
Note: pInfo works for STUDY design, but not for STUDY>info currently. Is the session set in the data variable or pInfo? If so, I think it would make more sense to do the same for the group for consistency.

**Comment by cll008** [comment] 2021-04-06 17:25
No worries Cedric. Thanks for confirming the character and numeric usage. Session is set in the data but based on the folder hierarchy of the BIDS dataset. I'm trying to make sure the tool works also when importing datasets that do not contain .set files (i.e. without the EEG data structure).

If you go into the participants.tsv of your BIDS folder, do you see that the group column entries have not been encoded correctly? They show up as "STX" and "SOH" for me in notepad++, and after I edit to "1" and "2" it populates in `STUDY> Edit Study Info` properly on import.

When you mention that `group` is recognized in design variables from .tsv file, do you mean `STUDY.design.variable`? For me right now it seems there is a bug in export when creating the participants.tsv.

**Comment by amisepa** [comment] 2021-04-06 18:56
Ok makes sense. 

> If you go into the participants.tsv of your BIDS folder, do you see that the group column entries have not been encoded correctly? They show up as "STX" and "SOH" for me in notepad++, and after I edit to "1" and "2" it populates in STUDY> Edit Study Info properly on import.

Yes, same here. And if I open it in Excel the first cell for group 1 is empty and the cell for group 2 has a rectangle in them. STUDY info also works after editing manually in notepad. 
So yes, it seems that the problem comes from the creation of the .tsv file in bids_export. I should have checked the .tsv file... FYI: this wasn't spotted by the online BIDS validator (https://bids-standard.github.io/bids-validator/ ). We should probably fix it there too.

I was setting the group information with: `pInfo(index,:) = {char(sInfo(iSubj).group)};`
but now with:   `pInfo(index,:) = {sInfo(iSubj).group};`
--> now the group number is present in the tsv file. However, it still doesn't populate well in STUDY info because it needs a string or character I am guessing? bids_export doesn't seem to work if I define the group as a string or characters.

Somehow, the group info is correctly imported in STUDY design even if the .tsv is incorrect:
![image](https://user-images.githubusercontent.com/58382227/113760123-b76f0a80-96ca-11eb-9d8e-0856bd017b02.png)

Cedric

**Comment by cll008** [comment] 2021-04-06 22:06
Is sInfo STUDY.datasetinfo? You might have to use `pInfo(index,:) = {num2str(sInfo(iSubj).group)}`

Looks like the the submenu from pop_studydesign branches into limo things, so maybe the text handling there is more robust.

**Comment by amisepa** [comment] 2021-04-06 22:26
Thanks,

No sInfo is my structure with subject file paths, session number, group number, bad channels, etc. I tried with num2str but that didn't work in STUDY info. In our example, it would be the same to just do:
```
pInfo(1,:) = {1};   %group 1
pInfo(2,:) = {2};   %group 2
```
The .tsv from export is now good in both situations ({1} and {num2str(1)}. I think the problem is now the bids_import that is expecting a different format for the group but I can't find which one it needs.

**Comment by cll008** [comment] 2021-04-06 22:34
https://github.com/sccn/bids-matlab-tools/blob/abb22f22da490d2650d32a2a3668548375341610/pop_importbids.m#L510

The group info is parsed and added to STUDY in this line, group is the last entry in `commands`
After editing the tsv, group populates in the pop_study GUI for me. Is this what you mean when you say STUDY info?

**Comment by amisepa** [comment] 2021-04-06 23:13
Hi Clement, 

I was just on a call with Arno for something else, and he fixed it ;) 

Thanks so much for your help!

@arnodelorme maybe we should add to the example how to export the group information (https://github.com/sccn/bids-matlab-tools/blob/abb22f22da490d2650d32a2a3668548375341610/bids_export_example.m)?
This input works now:
```
pInfo(index,:) = {1};   %group 1
pInfo(index,:) = {2};   %group 2
```

@arnodelorme FYI: the bids_validator didn't detect the problem.

Cedric

**Closed** 2021-04-12 23:03 UTC
